### ISSUE TITLE
TemplateEngine: caching different template-files with same uniqid

### ISSUE THREAD

**Issue by JayQ1982** [TiMESPLiNTER/tsFramework#8]
Sometimes, when system is running very fast, it might happen that different template-files get same uniqid in cache which means that one file will be overwritten by another, what leads to missing content.

Can be fixed by changing uniqid() to uniqid('', true) in TemplateEngine.class.php (line 312).

**Comment by TiMESPLiNTER** [comment]
Solved by new abstract `TemplateCacheStrategy` class and the implementation of `DirectoryTemplateCache`.

**Comment by TiMESPLiNTER** [comment]
Solved by new abstract `TemplateCacheStrategy` class and the implementation of `DirectoryTemplateCache`.
